"""Default assumptions for HVAC cash flow model."""

DEFAULTS = {
    # Model controls
    "start_year": 2025,
    "start_month": 1,
    "horizon_months": 60,
    "monthly_price_growth": 0.002,
    "monthly_cost_inflation": 0.0015,
    "seasonality_amplitude": 0.15,
    "peak_month": 7,
    # Staffing and ops
    "starting_techs": 8,
    "tech_hire_per_quarter": 1,
    "max_techs": 24,
    "calls_per_tech_per_day": 2.4,
    "work_days_per_month": 22,
    "avg_hours_per_tech_per_month": 160,
    "tech_wage_per_hour": 34.0,
    "payroll_burden_pct": 0.18,
    "tools_per_new_tech_capex": 3500.0,
    # Service revenue
    "avg_service_ticket": 345.0,
    "service_material_pct": 0.14,
    "attach_rate": 0.35,
    # Replacement revenue
    "repl_leads_per_tech_per_month": 3.5,
    "repl_close_rate": 0.42,
    "avg_repl_ticket": 9100.0,
    "repl_equipment_pct": 0.49,
    "permit_cost_per_repl_job": 130.0,
    "disposal_cost_per_repl_job": 80.0,
    "financing_penetration": 0.27,
    "financing_fee_pct": 0.045,
    # Maintenance program
    "enable_maintenance": True,
    "agreements_start": 400,
    "new_agreements_per_month": 22,
    "churn_annual_pct": 0.1,
    "maint_monthly_fee": 23.0,
    "cost_per_maint_visit": 72.0,
    "maint_visits_per_agreement_per_year": 1.8,
    # Marketing
    "paid_leads_mode": "per_tech",
    "paid_leads_per_month": 350,
    "paid_leads_per_tech_per_month": 28,
    "cost_per_lead": 90.0,
    "branding_fixed_monthly": 7000.0,
    # Fleet
    "trucks_per_tech": 1.0,
    "truck_payment_monthly": 740.0,
    "fuel_per_truck_monthly": 380.0,
    "maint_per_truck_monthly": 140.0,
    "truck_insurance_per_truck_monthly": 115.0,
    "truck_purchase_price": 54000.0,
    "capex_trucks_mode": "purchase_with_downpayment",
    "truck_downpayment_pct": 0.2,
    "truck_financed_pct": 0.8,
    # Overhead
    "office_payroll_monthly": 38000.0,
    "rent_monthly": 9000.0,
    "utilities_monthly": 2600.0,
    "insurance_monthly": 3200.0,
    "software_monthly": 2200.0,
    "other_fixed_monthly": 2500.0,
    # Working capital
    "ar_days": 25.0,
    "ap_days": 20.0,
    "inventory_days": 16.0,
    "starting_cash": 180000.0,
    # Debt
    "enable_term_loan": True,
    "loan_principal": 500000.0,
    "loan_annual_rate": 0.085,
    "loan_term_months": 60,
    "enable_loc": True,
    "loc_limit": 300000.0,
    "loc_annual_rate": 0.11,
    "min_cash_target": 100000.0,
    "loc_repay_buffer": 40000.0,
    # Distributions
    "enable_distributions": True,
    "distributions_pct_of_ebitda": 0.12,
    "distributions_only_if_cash_above": 180000.0,
}
